[program:openbox]
autorestart=true
command=dbus-launch --exit-with-session openbox
environment=DISPLAY=":1",HOME="%(ENV_USER_HOME)s",USER="%(ENV_CONTAINER_USER)s"
priority=30
user=%(ENV_CONTAINER_USER)s
stdout_logfile=/var/log/openbox.log
stderr_logfile=/var/log/openbox.err
