[program:xvfb]
autorestart=true
command=Xvfb :1 -screen 0 %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)sx24 -listen tcp -ac
priority=10
stdout_logfile=/var/log/xvfb.log
stderr_logfile=/var/log/xvfb.err
