[config]
single_click=0
auto_selection_delay=600
use_trash=1
confirm_del=1
confirm_trash=1
quick_exec=1

[ui]
always_show_tabs=0
max_tab_chars=32
win_width=640
win_height=480
splitter_pos=150
side_pane_mode=places
view_mode=list
show_hidden=0
sort=name;ascending;
toolbar=newtab;navigation;home;

[places]
places_home=1
places_desktop=1
places_root=0
places_computer=1
places_trash=1
places_applications=1
places_network=0

[terminal]
line=x-terminal-emulator
